language: node_js
node_js:
  - "7"
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
install:
  - yarn install
script:
  - yarn build
  - yarn test:ci
